- adds logic to unpack / pack
c80k/capnproto-dotnetcore pull request #14
Opened 2019-09-27 11:00 UTC by Almightie

Adds the ability to pack and unpack a memorystream or byte[] using the packing scheme explained [here](https://capnproto.org/encoding.html#packing). 

Packing using the `0xff` tag is not yet implemented.

2019-10-02 12:14 UTC, c80k commented on Capnp.Net.Runtime/PackedStream.cs
> +    public static class PackedStream
The name `PackedStream` might be misleading to users: It appears like a `Stream`-derived class which one can instantiate. In reality it is just a static utility class. Suggestion: Adding a plural "s" gives `PackedStreams` which might be less misleading. Or `PackedStreamUtil`?

2019-10-02 12:31 UTC, c80k requested changes
Thank for providing the PR! Packing is definitely a reasonable feature. Some requests:
- The optional `isPacked` parameter still imposes a breaking change, see review comment.
- If you add public methods to public classes, or parameters to existing public methods please provide according XML documentation.
- Please also add an automated test for the new feature.

One last (optional) thing: The current API is asymmetric with respect to reading and writing. While there is a dedicated extension method `ReadWireFrame` for `BinaryReader`, there is no such thing for `BinaryWriter`. With the packing feature the situation becomes worse, requiring an temporary `MemoryStream` instance. If there was an explicit method for writing a `WireFrame` to `BinaryWriter`, we could add an overload for packed frames. This would result in easier+faster code, since that method could pack *directly* to the `BinaryWriter`, without requiring a temporary `MemoryStream`. If you don't do it, I will factor that in later. Do you require `FramePump` to read/write packed frames?

2019-10-04 08:47 UTC, Almightie commented
@c80k: Thanks for your comments. Agreed on the optional parameter and naming comments. I think my code shows the amount of haste I had to make into getting this to work somewhat. 
Making the reading and writing symmetric makes sense. I'm not sure how reasonably feasible it is to pump a packed stream right into a capn'proto object without a temporary stream. I'm not very familiar with the WireFrame and FramePump classes yet to make any assumptions regarding that. 
I'll see if I can get some more time on this next week.

2019-10-05 14:29 UTC, c80k commented
`FramePump` handles sending and receiving messages over a `Stream`. This is the assumed standard use case on how an application does message I/O. The [Wiki page Example application (non RPC)](https://github.com/c80k/capnproto-dotnetcore/wiki/Example-application-(non-RPC)) gives a code example on that. If this assumption holds true, `FramePump` should get the ability to enable message packing/unpacking.

2025-01-15 14:35 UTC, closed without merging